server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8099/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  h2:
    console:
      enabled: true
  application:
    name: userservice

